### ISSUE TITLE
dedicated stylesheet

### ISSUE THREAD

**Issue by Davidsoff** [deanius/meteor-package-kitchen#14]
create a dedicated stylesheet or (optionally) remove all styling for the /kitchen page. Using the darkly bootstrap theme all the text turns white so you can't read anything :(

**Comment by chicagogrooves** [comment]
Can you show me how your darkly bootstrap theme is configured in your project? I thought `/kitchen` would not pick up styles from anywhere else. My guess is that you have a stylesheet in the `<head>` section of one of your pages, in the pre-iron-router way, so it is applying to every page rendered... I'm not sure what I could do to fix that, if that is the case.
